services:

  postgres:
    image: postgres:17
    container_name: secureflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: secureflow
      POSTGRES_PASSWORD: secureflow
      POSTGRES_DB: auth_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: